#ifndef LIGHT_MUSIC_CONFIG_H_
#define LIGHT_MUSIC_CONFIG_H_

typedef enum
{
    LM_SOUND_SIZE_64   = 64,
    LM_SOUND_SIZE_256  = 256,
    LM_SOUND_SIZE_1024 = 1024,
} lm_sound_size_e;

#define LM_CHANNEL_NUMBER     4
#define LM_SOUND_BUFFER_SIZE  LM_SOUND_SIZE_256
#define LM_STEREO_BUFFER_SIZE LM_SOUND_BUFFER_SIZE * 2
#define LM_FFT_BUFFER_SIZE    LM_SOUND_BUFFER_SIZE
#define LM_USE_PLAYBACK       1

#endif/*LIGHT_MUSIC_CONFIG_H_*/
