#ifndef LIGHT_MUSIC_CONFIG_H_
#define LIGHT_MUSIC_CONFIG_H_

#define LM_CHANNEL_NUMBER     4
#define LM_SOUND_BUFFER_SIZE  1024
#define LM_STEREO_BUFFER_SIZE LM_SOUND_BUFFER_SIZE * 2
#define LM_FFT_BUFFER_SIZE    LM_SOUND_BUFFER_SIZE / 2
#define LM_USE_PLAYBACK       1

#endif/*LIGHT_MUSIC_CONFIG_H_*/
